### PR TITLE
Allow fetching queues with query GET arguments

### LINKED ISSUE #89: Support specifying query parameters
Most management endpoints support limiting the number of fields you get back in the API response, using `?fields=` 

Is this something that is planned to be added? :)

### PR DESCRIPTION
**Pull request by jippi**
Fixes #89.

### CODE REVIEW

**Comment by michaelklishin** [comment]
It looks OK; can we please add at least one test?

**Comment by jippi** [comment]
@michaelklishin sure thing! Just wanted to make sure my approach was acceptable before learning how to write tests in Go :)

**Comment by michaelklishin** [comment]
@jippi 👍

**Comment by jippi** [comment]
@michaelklishin test added and things should be passing like a happy camper :)

**Pull request merged**
