### PR TITLE
Adds Shovel support

### PR DESCRIPTION
**Pull request by Jakauppila**
Adds supports for shovels

- ListShovels
- ListShovelsIn
- GetShovel
- DeclareShovel
- DeleteShovel

Also enabled 'rabbitmq_shovel' and 'rabbitmq_shovel_management' plugins in before_build as well as created a .bat equivalent for running tests on Windows.

As far as tests are concerned, I just have the one that creates a shovel, checks the config, then deletes it. Are there other tests you would like to see?

Fixes https://github.com/michaelklishin/rabbit-hole/issues/91

As a side note, I get an error with the second eval.

```
call %RABBITHOLE_RABBITMQCTL% eval "supervisor2:terminate_child(rabbit_mgmt_agent_sup_sup, rabbit_mgmt_agent_sup), application:set_env(rabbitmq_management_agent, sample_retention_policies, [{global, [{605, 1}]}, {basic, [{605, 1}]}, {detailed, [{10, 1}]}]), rabbit_mgmt_agent_sup_sup:start_child()."

Error: {noproc,{gen_server,call,
                           [rabbit_mgmt_agent_sup_sup,
                            {terminate_child,rabbit_mgmt_agent_sup},
                            infinity]}}
```

### CODE REVIEW

**Comment by Jakauppila** [comment]
Should DeclareShovel and DeleteShovel be renamed to DeclareDynamicShovel and DeleteDynamicShovel just to eliminate any confusion with static shovels?

**Comment by Jakauppila** [comment]
@michaelklishin Any thoughts on this?

**Comment by michaelklishin** [comment]
I think the confusion with static shovels is unlikely.

**Comment by michaelklishin** [comment]
Thank you.

**Pull request merged**
