### PR TITLE
Correct Shovel struct field types

### PR DESCRIPTION
**Pull request by pathcl**
DestinationURI/SourceURI it's an slice at least in rabbitmq 3.8.9

issue related: https://github.com/michaelklishin/rabbit-hole/issues/103

### CODE REVIEW

**Comment by michaelklishin** [comment]
@pathcl thank you. How can I reproduce the issue this strives to address?

**Comment by michaelklishin** [comment]
A really basic Shovel in 3.8 uses "singular" values for source and destination URIs:

``` json
[
  {
    "node": "rabbit@warp10",
    // ...
    "name": "amqp://",
    "vhost": "/",
    "type": "dynamic",
    "state": "running",
    "src_uri": "amqp://",
    "src_protocol": "amqp091",
    "dest_protocol": "amqp091",
    "dest_uri": "amqp://",
    "src_queue": "src-queue",
    "dest_queue": "dest-queue"
  }
].
```

**Comment by michaelklishin** [comment]
I now realize the difference: the above is from the Shovel management HTTP API endpoint and #171 uses the runtime parameters endpoint, which indeed can use slightly different values.

**Comment by pathcl** [comment]
@michaelklishin I also noticed if we use passwords like '#123' rabbit will complain with 400 error since we're not urlencoding

**Comment by michaelklishin** [comment]
Percent-encoding of various parts of URIs is a separate issue. Some would argue that libraries should not do that at all.

**Review by michaelklishin — CHANGES_REQUESTED** [review]
With this PR, tests cannot compile because they provide a single URI (which is still perfectly valid) and not an array.

We have to support both types for these fields. I'm looking into it.

**Pull request closed without merging**
