### PR TITLE
Fix go mod failures

### PR DESCRIPTION
**Pull request by gerhard**
This is expected to fix:

- [x] [server-release:v3.8.x rabbit-hole:master](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x/jobs/test-with-rabbit-hole:master/builds/260)
- [x] [server-release:v3.7.x rabbit-hole:master](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.7.x/jobs/test-with-rabbit-hole:master/builds/302)

Will ensure all pipelines pass with the fork before submitting this as a regular PR (currently a draft).

### CODE REVIEW

**Comment by gerhard** [comment]
I've just realised that I can only address `master` failures, since release will require you to tag a new release.

3.8 is now passing with these changes:

image

**Comment by gerhard** [comment]
server-release:3.7.x is passing as well:
image

**Comment by gerhard** [comment]
Had to revert the pipelines, merging this will fix the current failures linked in the PR description

**Comment by michaelklishin** [comment]
Thank you!

**Comment by gerhard** [comment]
Now that master is passing, are you going to tag a new release so that [releases tests](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.7.x/jobs/test-with-rabbit-hole:release/builds/290) can pass as well?

**Comment by gerhard** [comment]
I just noticed that this broke the Travis build. Will have a go at fixing it.

**Pull request merged**
