### PR TITLE
Add vhost description and tags

### PR DESCRIPTION
**Pull request by daktari**
Add possibility to set Description and Tags in vhost creation.

### CODE REVIEW

**Comment by pserranoa** [comment]
+1

**Review by michaelklishin — CHANGES_REQUESTED** [review]
I don't think virtual host tags were ever returned as a comma-separated string. Let's just support regular arrays since that's what I see returned on RabbitMQ 3.8.

User tags have to do this because historically the value there was a comma-separated array.

**Comment by michaelklishin** [comment]
Thank you. I think this is a no-brainer to add but we can simplify the marshalling part.

**Comment by michaelklishin** [comment]
Interesting, looks like this PR has helped me find a subtle bug in the `PUT /api/vhosts/{vhost}` endpoint. I'm investigating.

**Comment by michaelklishin** [comment]
Confirmed a bug and that the marshalling code this PR includes is indeed necessary for it.

**Review by michaelklishin — APPROVED** [review]

**Comment by daktari** [comment]
Thank you!

**Pull request merged**
