### PR TITLE
add Client HTTP timeout

### PR DESCRIPTION
**Pull request by pierrre**
add Client HTTP timeout

\+ simplify the code

### CODE REVIEW

**Comment by pierrre** [comment]
Reason for this PR: sometimes the RabbitMQ HTTP API hangs indefinitely in my tests (on Travis).
I don't understand exactly why.

Anyway, I think it's great to allow the user to set a timeout on HTTP request.
It would be better to add `context` support, but it would require large changes in the code.

**Comment by michaelklishin** [comment]
I completely agree, having timeouts is a very good idea. Thank you.

**Comment by michaelklishin** [comment]
`context` support would be welcomed. Version will have to be bumped to 2.0 but I'm completely open to supporting two release series.

**Comment by pierrre** [comment]
thank you !

**Pull request merged**
